#!/bin/sh

# install brew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# install uv
curl -LsSf https://astral.sh/uv/install.sh | sh

# install brew cli tools
brew install yadm
brew install lsd
brew install bat
brew install fd
brew install mpv
brew install dust
brew install duf
brew install direnv
brew install --cask font-fira-code-nerd-font

# decrypt
yadm decrypt
