#!/bin/sh

# install brew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# install uv
curl -LsSf https://astral.sh/uv/install.sh | sh

# install brew cli tools
brew install yadm
brew install lsd
brew install bat
brew install fd
brew install mpv
brew install dust
brew install duf
brew install direnv
brew install --cask font-fira-code-nerd-font
brew install --cask visual-studio-code
brew install --cask bettertouchtool
brew install --cask kitty
brew install --cask wezterm

# neovim
brew install neovim
brew install luaver
brew install ripgrep
brew install astgrep
brew install lazygit
brew install wget

# brew install --cask bambu-studio
# brew install --cask orcaslicer

# decrypt
yadm decrypt
